name: nokaut
version: 1.10
main: me.smaks6.nokaut.Main
author: smaks6
website: https://www.spigotmc.org/resources/nokaut.85152/
description: Plugin jest kopia pluginu na nokaut z km

commands:
  zginodrazu:
    aliases: [zo, deathnow, dn]
    permission: nokaut.deathnow
  nokaut:
    aliases: nk
    permission: nokaut.admin

permissions:
  nokaut.deathnow:
    description: Permissions to the command deathnow and zginodrazu
    default: true
  nokaut.admin:
    description: Permissions to the admin command
    default: op